



User.create(:username => "cdub", :password => "dinner", :email => "cwood32k@gmail.com", :first_name => "Chris", :last_name => "Wood", :wins => 10, :losses => 10, :ties => 1, :nfl_wins => 1, :nfl_losses => 2, :nfl_ties => 4, :nba_wins => 7, :nba_losses => 10, :nba_ties => 13, :mlb_wins => 16, :mlb_losses => 12, :mlb_ties => 21, :nhl_wins => 9, :nhl_losses => 5, :nhl_ties => 1, :accept_terms => true, :bankroll => 200, :money => 25)
User.create(:username => "sports_fan1", :password => "dinner", :email => "fan1@mail.com", :first_name => "Ron", :last_name => "Artest", :wins => 100, :losses => 35, :ties => 1, :nfl_wins => 21, :nfl_losses => 31, :nfl_ties => 1, :nba_wins => 17, :nba_losses => 18, :nba_ties => 1, :mlb_wins => 2, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 19, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 2500)
User.create(:username => "sports_fan2", :password => "dinner", :email => "fan2@mail.com", :first_name => "Kobe", :last_name => "Bryant", :wins => 7, :losses => 21, :ties => 1, :nfl_wins => 1, :nfl_losses => 2, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 4, :nba_ties => 1, :mlb_wins => 6, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 2, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 20)
User.create(:username => "sports_fan3", :password => "dinner", :email => "fan3@mail.com", :first_name => "test", :last_name => "user", :wins => 2, :losses => 12, :ties => 1, :nfl_wins => 8, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 8, :nba_losses => 8, :nba_ties => 1, :mlb_wins => 12, :mlb_losses => 6, :mlb_ties => 1, :nhl_wins => 10, :nhl_losses => 5, :nhl_ties => 1,  :accept_terms => true, :bankroll => 5)
User.create(:username => "sports_fan4", :password => "dinner", :email => "fan4@mail.com", :first_name => "test", :last_name => "user", :wins => 18, :losses => 12, :ties => 1, :nfl_wins => 5, :nfl_losses => 4, :nfl_ties => 1, :nba_wins => 6, :nba_losses => 2, :nba_ties => 1, :mlb_wins => 13, :mlb_losses => 15, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 10, :nhl_ties => 1,  :accept_terms => true, :bankroll => 565)
User.create(:username => "sports_fan5", :password => "dinner", :email => "fan5@mail.com", :first_name => "test", :last_name => "user", :wins => 56, :losses => 100, :ties => 1, :nfl_wins => 32, :nfl_losses => 24, :nfl_ties => 1, :nba_wins => 15, :nba_losses => 44, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 2, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 1800)
User.create(:username => "sports_fan6", :password => "dinner", :email => "fan6@mail.com", :first_name => "test", :last_name => "user", :wins => 75, :losses => 75, :ties => 1, :nfl_wins => 14, :nfl_losses => 7, :nfl_ties => 2, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 11, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 1000)
User.create(:username => "sports_fan7", :password => "dinner", :email => "fan7@mail.com", :first_name => "test", :last_name => "user", :wins => 88, :losses => 25, :ties => 1, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 1500)
User.create(:username => "sports_fan8", :password => "dinner", :email => "fan8@mail.com", :first_name => "test", :last_name => "user", :wins => 22, :losses => 10, :ties => 1, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 1500)
User.create(:username => "sports_fan9", :password => "dinner", :email => "fan9@mail.com", :first_name => "test", :last_name => "user", :wins => 22, :losses => 22, :ties => 1, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 200)
User.create(:username => "sports_fan10", :password => "dinner", :email => "fan10@mail.com", :first_name => "test", :last_name => "user", :wins => 65, :losses => 150, :ties => 1, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 300)
User.create(:username => "sports_fan11", :password => "dinner", :email => "fan11@mail.com", :first_name => "test", :last_name => "user", :wins => 4, :losses => 1, :ties => 1, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 400)

User.create(:username => "basketball1", :password => "dinner", :email => "fan12@mail.com", :first_name => "Ron", :last_name => "Artest", :wins => 100, :losses => 35, :ties => 13, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 25300)
User.create(:username => "basketball2", :password => "dinner", :email => "fan13@mail.com", :first_name => "Kobe", :last_name => "Bryant", :wins => 22432, :losses => 321, :ties => 12, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 232034)
User.create(:username => "basketball3", :password => "dinner", :email => "fan14@mail.com", :first_name => "test", :last_name => "user", :wins => 3422, :losses => 1342, :ties => 13, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 52653)
User.create(:username => "football4", :password => "dinner", :email => "fan24@mail.com", :first_name => "test", :last_name => "user", :wins => 1238, :losses => 112, :ties => 12, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 562655)
User.create(:username => "football5", :password => "dinner", :email => "fan15@mail.com", :first_name => "test", :last_name => "user", :wins => 56, :losses => 100, :ties => 6, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 12300)
User.create(:username => "football_fan6", :password => "dinner", :email => "fan16@mail.com", :first_name => "test", :last_name => "user", :wins => 735, :losses => 745, :ties => 22, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 1005620)
User.create(:username => "baseball_fan", :password => "dinner", :email => "fan17@mail.com", :first_name => "test", :last_name => "user", :wins => 838, :losses => 265, :ties => 1, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 1500)
User.create(:username => "baseball_fan2", :password => "dinner", :email => "fan18@mail.com", :first_name => "test", :last_name => "user", :wins => 212, :losses => 110, :ties => 33, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 152300)
User.create(:username => "baseball_fan3", :password => "dinner", :email => "fan19@mail.com", :first_name => "test", :last_name => "user", :wins => 22, :losses => 22, :ties => 2, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 290)
User.create(:username => "baseball_fan4", :password => "dinner", :email => "fan20@mail.com", :first_name => "test", :last_name => "user", :wins => 6445, :losses => 1540, :ties => 5, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 30230)
User.create(:username => "gambler", :password => "dinner", :email => "fan21@mail.com", :first_name => "test", :last_name => "user", :wins => 4, :losses => 1, :ties => 1, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 400)

User.create(:username => "high_roller1", :password => "dinner", :email => "fan21@mail.com", :first_name => "Ron", :last_name => "Artest", :wins => 100, :losses => 35, :ties => 13, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 96300)
User.create(:username => "high_roller2", :password => "dinner", :email => "fan22@mail.com", :first_name => "Kobe", :last_name => "Bryant", :wins => 22432, :losses => 321, :ties => 12, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 23605)
User.create(:username => "high_roller3", :password => "dinner", :email => "fan23@mail.com", :first_name => "test", :last_name => "user", :wins => 3422, :losses => 132, :ties => 13, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 53)
User.create(:username => "high_roller4", :password => "dinner", :email => "fan25@mail.com", :first_name => "test", :last_name => "user", :wins => 1238, :losses => 12, :ties => 12, :nfl_wins => 75, :nfl_losses => 21, :nfl_ties => 1, :nba_wins => 93, :nba_losses => 100, :nba_ties => 1, :mlb_wins => 16, :mlb_losses => 17, :mlb_ties => 0, :nhl_wins => 0, :nhl_losses => 3, :nhl_ties => 0,  :accept_terms => true, :bankroll => 5626)
User.create(:username => "high_roller5", :password => "dinner", :email => "fan26@mail.com", :first_name => "test", :last_name => "user", :wins => 56, :losses => 10, :ties => 6, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 1230)
User.create(:username => "high_roller6", :password => "dinner", :email => "fan27@mail.com", :first_name => "test", :last_name => "user", :wins => 735, :losses => 45, :ties => 22, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 10620)
User.create(:username => "high_roller7", :password => "dinner", :email => "fan28@mail.com", :first_name => "test", :last_name => "user", :wins => 838, :losses => 26, :ties => 1, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 1501)
User.create(:username => "high_roller8", :password => "dinner", :email => "fan29@mail.com", :first_name => "test", :last_name => "user", :wins => 212, :losses => 10, :ties => 33, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 15200)
User.create(:username => "high_roller9", :password => "dinner", :email => "fan30@mail.com", :first_name => "test", :last_name => "user", :wins => 22, :losses => 22, :ties => 2, :nfl_wins => 101, :nfl_losses => 65, :nfl_ties => 2, :nba_wins => 154, :nba_losses => 200, :nba_ties => 1, :mlb_wins => 5, :mlb_losses => 4, :mlb_ties => 0, :nhl_wins => 0, :nhl_losses => 0, :nhl_ties => 0,  :accept_terms => true, :bankroll => 2940)
User.create(:username => "high_roller10", :password => "dinner", :email => "fan31@mail.com", :first_name => "test", :last_name => "user", :wins => 6445, :losses => 10, :ties => 5, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 300)
User.create(:username => "high_roller11", :password => "dinner", :email => "fan32@mail.com", :first_name => "test", :last_name => "user", :wins => 4, :losses => 1, :ties => 1, :nfl_wins => 1, :nfl_losses => 1, :nfl_ties => 1, :nba_wins => 1, :nba_losses => 1, :nba_ties => 1, :mlb_wins => 1, :mlb_losses => 1, :mlb_ties => 1, :nhl_wins => 1, :nhl_losses => 1, :nhl_ties => 1,  :accept_terms => true, :bankroll => 40)


